# Site settings
title: Dadario - Developer Blog
email: dadario@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place to describe current problems and solutions.
  Motivado pelo desenvolvimento ocorrendo no dia-a-dia e com muitas conversas
  entre amigos programadores
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dadario.github.io" # the base hostname & protocol for your site
twitter_username: dadario
github_username:  dadario

# Build settings
markdown: kramdown
